# Generated by Django 3.2.9 on 2022-04-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='mobile',
            new_name='phone',
        ),
    ]
