# Generated by Django 3.2.9 on 2022-04-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_mobile_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guest_Reservation', to='tickets.movie'),
        ),
    ]
